create table if not exists public.items (
    id bigint generated by default as identity primary key,
    name text not null unique,
    rarity text not null check (rarity in ('common', 'uncommon', 'rare', 'epic', 'legendary', 'mythical')),
    item_value integer not null default 0 check (item_value >= 0),
    image_url text,
    created_at timestamptz not null default now()
);

alter table public.items enable row level security;

drop policy if exists "Items are readable by everyone" on public.items;
create policy "Items are readable by everyone"
    on public.items for select
    using (true);

drop policy if exists "Items can be created from admin panel" on public.items;
create policy "Items can be created from admin panel"
    on public.items for insert
    with check (true);

drop policy if exists "Items can be updated from admin panel" on public.items;
create policy "Items can be updated from admin panel"
    on public.items for update
    using (true)
    with check (true);

alter table public.case_items
    add column if not exists item_id bigint references public.items(id) on delete cascade;

alter table public.case_items drop constraint if exists case_items_rarity_check;

alter table public.case_items
    add constraint case_items_rarity_check
    check (rarity in ('common', 'uncommon', 'rare', 'epic', 'legendary', 'mythical'));

alter table public.case_items enable row level security;

drop policy if exists "Case items are readable by everyone" on public.case_items;
create policy "Case items are readable by everyone"
    on public.case_items for select
    using (true);

drop policy if exists "Case items can be created from admin panel" on public.case_items;
create policy "Case items can be created from admin panel"
    on public.case_items for insert
    with check (true);

drop policy if exists "Case items can be updated from admin panel" on public.case_items;
create policy "Case items can be updated from admin panel"
    on public.case_items for update
    using (true)
    with check (true);

create index if not exists case_items_item_id_idx on public.case_items(item_id);
create index if not exists case_items_case_id_idx on public.case_items(case_id);