create table if not exists public.items (
    id bigint generated by default as identity primary key,
    name text not null unique,
    rarity text not null check (rarity in ('common', 'uncommon', 'rare', 'epic', 'legendary', 'mythical')),
    item_value integer not null default 0 check (item_value >= 0),
    image_url text,
    created_at timestamptz not null default now()
);

alter table public.items enable row level security;

drop policy if exists "Items are readable by everyone" on public.items;
create policy "Items are readable by everyone"
    on public.items for select
    using (true);

drop policy if exists "Items can be created from admin panel" on public.items;
create policy "Items can be created from admin panel"
    on public.items for insert
    with check (true);

drop policy if exists "Items can be updated from admin panel" on public.items;
create policy "Items can be updated from admin panel"
    on public.items for update
    using (true)
    with check (true);

alter table public.case_items
    add column if not exists item_id bigint references public.items(id) on delete cascade;

alter table public.case_items drop constraint if exists case_items_rarity_check;

alter table public.case_items
    add constraint case_items_rarity_check
    check (rarity in ('common', 'uncommon', 'rare', 'epic', 'legendary', 'mythical'));

alter table public.case_items enable row level security;

drop policy if exists "Case items are readable by everyone" on public.case_items;
create policy "Case items are readable by everyone"
    on public.case_items for select
    using (true);

drop policy if exists "Case items can be created from admin panel" on public.case_items;
create policy "Case items can be created from admin panel"
    on public.case_items for insert
    with check (true);

drop policy if exists "Case items can be updated from admin panel" on public.case_items;
create policy "Case items can be updated from admin panel"
    on public.case_items for update
    using (true)
    with check (true);

create index if not exists case_items_item_id_idx on public.case_items(item_id);
create index if not exists case_items_case_id_idx on public.case_items(case_id);

alter table public.case_openings enable row level security;

drop policy if exists "Case openings are readable by the app" on public.case_openings;
create policy "Case openings are readable by the app"
    on public.case_openings for select
    using (true);

drop policy if exists "Case openings can be created by the app" on public.case_openings;
create policy "Case openings can be created by the app"
    on public.case_openings for insert
    with check (
        exists (
            select 1
            from public.profiles
            where public.profiles.id = case_openings.user_id
        )
    );

create or replace function public.sell_inventory_item(p_inventory_id integer, p_user_id integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    inventory_item public.inventory%rowtype;
    updated_balance integer;
begin
    select * into inventory_item
    from public.inventory
    where id = p_inventory_id and user_id = p_user_id
    for update;

    if not found then
        raise exception 'Предмет не найден в инвентаре игрока';
    end if;

    update public.profiles
    set balance = balance + (inventory_item.item_value * inventory_item.quantity),
        updated_at = now()
    where id = p_user_id
    returning balance into updated_balance;

    if not found then
        raise exception 'Профиль игрока не найден';
    end if;

    delete from public.inventory where id = p_inventory_id;
    return updated_balance;
end;
$$;

grant execute on function public.sell_inventory_item(integer, integer) to anon, authenticated;